- name: Ensure Plex dependencies are installed
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - gpg
      - sudo
    update_cache: true

- name: Install required packages for VA-API and OpenCL
  ansible.builtin.apt:
    name:
      - va-driver-all
      - ocl-icd-libopencl1
      - intel-opencl-icd
      - vainfo
      - intel-gpu-tools
    state: present
    update_cache: true

- name: Ensure plex group with GID 1000 exists
  ansible.builtin.group:
    name: plex
    gid: 1000
    state: present

- name: Ensure plex group with GID 44 exists
  ansible.builtin.group:
    name: video
    gid: 44
    state: present

- name: Ensure plex group with GID 108 exists
  ansible.builtin.group:
    name: render
    gid: 108
    state: present

- name: Update Plex service user to UID 1000 and GID 1000
  ansible.builtin.user:
    name: plex
    uid: 1000
    group: plex

- name: Add Root user to video group for QSV access
  ansible.builtin.user:
    name: root
    groups: video,render
    append: true

- name: Add Plex user to video group for QSV access
  ansible.builtin.user:
    name: plex
    groups: video,render
    append: true

- name: Ensure /opt/plex directory exists
  ansible.builtin.file:
    path: /opt/plex
    state: directory
    mode: '775'

# - name: Change group ownership of /dev/dri to video (only for privileged containers)
#   ansible.builtin.file:
#     path: /dev/dri
#     group: video
#     state: directory
#     mode: '775'

# - name: Change permissions for files in /dev/dri (only for privileged containers)
#   ansible.builtin.file:
#     path: /dev/dri
#     mode: '660'
#     recurse: true

# Step 1: Set up Plex Media Server repository key using shell
- name: Add Plex Media Server repository key
  ansible.builtin.shell: "curl -s https://downloads.plex.tv/plex-keys/PlexSign.key | apt-key add -"
  register: add_plex_key
  changed_when: "'OK' in add_plex_key.stdout"

# Step 2: Add Plex repository
- name: Add Plex Media Server repository
  ansible.builtin.apt_repository:
    repo: "deb https://downloads.plex.tv/repo/deb/ public main"
    state: present
    filename: plexmediaserver

# Step 3: Update apt cache
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

# Step 4: Install Plex Media Server
- name: Install Plex Media Server
  ansible.builtin.apt:
    name: plexmediaserver
    state: present

# Step 5: Ensure Plex service is enabled and running
- name: Ensure Plex service is enabled and running
  ansible.builtin.systemd:
    name: plexmediaserver
    enabled: true
    state: started
