- name: Install prerequisites for Sonarr
  ansible.builtin.apt:
    name:
      - curl
      - sudo
      - sqlite3
      - unzip
    state: present
    update_cache: true

- name: Ensure /var/lib/sonarr directory exists
  ansible.builtin.file:
    path: /var/lib/sonarr
    state: directory
    mode: '775'

- name: Download Sonarr
  ansible.builtin.get_url:
    url: https://services.sonarr.tv/v1/download/main/latest?version=4&os=linux&arch=x64
    dest: /opt/sonarr.tar.gz
    mode: '775'

- name: Extract Sonarr
  ansible.builtin.unarchive:
    src: /opt/sonarr.tar.gz
    dest: /opt/
    remote_src: true
    mode: '775'

- name: Clean up the downloaded tarball
  ansible.builtin.file:
    path: /opt/sonarr.tar.gz
    state: absent

- name: Change ownership of Sonarr directory
  ansible.builtin.file:
    path: /opt/Sonarr
    mode: '775'
    recurse: true

- name: Create Sonarr service
  ansible.builtin.copy:
    dest: /etc/systemd/system/sonarr.service
    mode: '644'
    content: |
      [Unit]
      Description=Sonarr Daemon
      After=syslog.target network.target

      [Service]
      Type=simple
      ExecStart=/opt/Sonarr/Sonarr -nobrowser -data=/var/lib/sonarr/
      TimeoutStopSec=20
      KillMode=process
      Restart=on-failure
      LimitNOFILE=32768

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start and enable Sonarr service
  ansible.builtin.systemd:
    name: sonarr
    enabled: true
    state: started

- name: Cleaning up unused and unnecessary package files
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
