all:
  hosts:
    plex:
      ansible_host: "192.168.1.101" 
    radarr:
      ansible_host: "192.168.1.102"
    sonarr:
      ansible_host: "192.168.1.103"
    bazarr:
      ansible_host: "192.168.1.104"
    lidarr:
      ansible_host: "192.168.1.105"
    prowlarr:
      ansible_host: "192.168.1.106"
    readarr:
      ansible_host: "192.168.1.107"
    overseerr:
      ansible_host: "192.168.1.108"
    flaresolverr:
      ansible_host: "192.168.1.109"
    tautulli:
      ansible_host: "192.168.1.110"
    calibre_web:
      ansible_host: "192.168.1.111"
    kavita:
      ansible_host: "192.168.1.112"
    qbittorrent:
      ansible_host: "192.168.1.113"
    homepage:
      ansible_host: "192.168.1.114"
    gotify:
      ansible_host: "192.168.1.115"
    proxmox:
      ansible_host: "192.168.1.12"


  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_command_timeout: 70
    become: true