---
- name: restart service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: restarted
    daemon_reload: true

- name: reload service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: reloaded
