- name: Install prerequisites for Tautulli
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - git
    state: present
    update_cache: true

- name: Ensure tautulli user and group with UID and GID 1000 exist
  ansible.builtin.user:
    name: tautulli
    uid: 1000
    group: tautulli
    create_home: false
    shell: /usr/sbin/nologin

- name: Ensure tautulli group with GID 1000 exists
  ansible.builtin.group:
    name: tautulli
    gid: 1000
    state: present

- name: Clone Tautulli repository
  ansible.builtin.git:
    repo: https://github.com/Tautulli/Tautulli.git
    dest: /opt/tautulli
    version: master

- name: Create systemd service for Tautulli
  ansible.builtin.copy:
    dest: /etc/systemd/system/tautulli.service
    mode: '644'
    content: |
      [Unit]
      Description=Tautulli Daemon
      After=network.target

      [Service]
      ExecStart=/usr/bin/python3 /opt/tautulli/Tautulli.py
      User=tautulli
      Group=tautulli
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
      LimitNOFILE=32768

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Tautulli service
  ansible.builtin.systemd:
    name: tautulli
    enabled: true
    state: started
