- name: Install prerequisites for Kavita
  ansible.builtin.apt:
    name:
      - wget
      - unzip
      - curl
      - sudo
    state: present
    update_cache: true

- name: Get the latest Kavita release version
  ansible.builtin.shell: |
    curl -s https://api.github.com/repos/Kareadita/Kavita/releases/latest | grep "tag_name" | awk '{print substr($2, 2, length($2)-3) }'
  register: kavita_release

- name: Download and extract Kavita
  ansible.builtin.shell: |
    curl -fsSL https://github.com/Kareadita/Kavita/releases/download/{{ kavita_release.stdout }}/kavita-linux-x64.tar.gz | tar -xvzf - --no-same-owner
  args:
    chdir: /opt

- name: Ensure user and group has correct rights over extracted files
  ansible.builtin.file:
    path: /opt/Kavita
    mode: '775'
    recurse: true
  become: true

- name: Create systemd service for Kavita
  ansible.builtin.copy:
    dest: /etc/systemd/system/kavita.service
    mode: '644'
    content: |
      [Unit]
      Description=Kavita Daemon
      After=network.target

      [Service]
      Type=simple
      User=root
      WorkingDirectory=/opt/Kavita
      ExecStart=/opt/Kavita/Kavita
      TimeoutStopSec=20
      KillMode=process
      Restart=on-failure
      LimitNOFILE=32768

      [Install]
      WantedBy=multi-user.target

- name: Ensure all files in /opt/Kavita are executable
  ansible.builtin.file:
    path: /opt/Kavita/
    mode: 'u+x'
    recurse: true

- name: Change ownership of all files in /opt/Kavita to root
  ansible.builtin.file:
    path: /opt/Kavita/
    owner: root
    recurse: true

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Kavita service
  ansible.builtin.systemd:
    name: kavita
    enabled: true
    state: started

- name: Cleaning up unused and unnecessary package files
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
