- name: Install prerequisites for Tautulli
  ansible.builtin.apt:
    name:
      - curl
      - sudo
      - git
      - pip
      - python3
      - python3-dev
      - python3-pip
    state: present
    update_cache: true

- name: Remove EXTERNALLY-MANAGED files from Python directories
  ansible.builtin.shell: "rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED"
  register: return_remove_python

- name: Ensure /opt/tautulli directory exists
  ansible.builtin.file:
    path: /opt/tautulli
    state: directory
    mode: '775'

- name: Clone Tautulli repository # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/Tautulli/Tautulli.git
    dest: /opt/tautulli
  timeout: 100

- name: Change ownership of Tautulli directory
  ansible.builtin.file:
    path: /opt/tautulli
    mode: '775'
    recurse: true

- name: Install Tautulli requirements globally with pip
  ansible.builtin.shell: "pip install --break-system-packages -r /opt/tautulli/requirements.txt && pip install --break-system-packages pyopenssl"
  register: return_python_requirement
  ignore_errors: true
  failed_when: "'error' in return_python_requirement.stderr"

- name: Debug Python install errors if any
  ansible.builtin.debug:
    msg: "{{ return_python_requirement.stderr }}"

- name: Create systemd service for Tautulli
  ansible.builtin.copy:
    dest: /etc/systemd/system/tautulli.service
    mode: '644'
    content: |
      [Unit]
      Description=Tautulli Daemon
      After=syslog.target network.target

      [Service]
      WorkingDirectory=/opt/tautulli/
      Restart=on-failure
      RestartSec=5
      Type=simple
      ExecStart=/usr/bin/python3 /opt/tautulli/Tautulli.py
      KillSignal=SIGINT
      TimeoutStopSec=20
      SyslogIdentifier=tautulli
      LimitNOFILE=32768

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Tautulli service
  ansible.builtin.systemd:
    name: tautulli
    enabled: true
    state: started

- name: Cleaning up unused and unnecessary package files
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
