- name: Install prerequisites for Lidarr
  ansible.builtin.apt:
    name:
      - curl
      - libmono-cil-dev
      - mediainfo
      - sqlite3
      - unzip
    state: present
    update_cache: true

- name: Ensure /var/lib/lidarr directory exists
  ansible.builtin.file:
    path: /var/lib/lidarr
    state: directory
    mode: '775'

- name: Download Lidarr
  ansible.builtin.get_url:
    url: http://lidarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64
    dest: /opt/lidarr.tar.gz
    mode: '775'

- name: Extract Lidarr
  ansible.builtin.unarchive:
    src: /opt/lidarr.tar.gz
    dest: /opt/
    remote_src: true
    mode: '775'

- name: Ensure user and group has correct rights over extracted files
  ansible.builtin.file:
    path: /opt/Lidarr
    mode: '775'
    recurse: true

- name: Clean up the downloaded tarball
  ansible.builtin.file:
    path: /opt/lidar.tar.gz
    state: absent

- name: Create systemd service for Lidarr
  ansible.builtin.copy:
    dest: /etc/systemd/system/lidarr.service
    mode: '644'
    content: |
      [Unit]
      Description=Lidarr Daemon
      After=syslog.target network.target

      [Service]
      UMask=0002
      Type=simple
      ExecStart=/opt/Lidarr/Lidarr -nobrowser -data=/var/lib/lidarr/
      TimeoutStopSec=20
      KillMode=process
      Restart=on-failure
      LimitNOFILE=16384

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Lidarr service
  ansible.builtin.systemd:
    name: lidarr
    enabled: true
    state: started

- name: Cleaning up unused and unnecessary package files
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
