- name: Install prerequisites for Overseerr
  ansible.builtin.apt:
    name:
      - curl
      - unzip
      - sudo
      - git
      - ca-certificates
      - gnupg
    state: present
    update_cache: true

- name: Ensure the Node.js repository is added
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    state: present
    keyring: /etc/apt/keyrings/nodesource.gpg

- name: Create sources.list.d directory if not exists
  ansible.builtin.file:
    path: /etc/apt/sources.list.d
    state: directory
    mode: '755'

- name: Add Node.js repository
  ansible.builtin.copy:
    content: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main"
    dest: /etc/apt/sources.list.d/nodesource.list
    mode: '644'

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: present

- name: Install Yarn globally
  community.general.npm:
    name: yarn
    global: true
    state: present

- name: Ensure /opt/overseerr directory exists
  ansible.builtin.file:
    path: /opt/overseerr
    state: directory
    mode: '775'

- name: Clone the Overseerr repository
  ansible.builtin.git:
    repo: https://github.com/sct/overseerr.git
    dest: /opt/overseerr
    update: false

- name: Install dependencies for Overseerr using Yarn
  ansible.builtin.command:
    cmd: yarn install
    chdir: /opt/overseerr

- name: Build Overseerr
  ansible.builtin.command:
    cmd: yarn build
    chdir: /opt/overseerr

- name: Create systemd service for Overseerr
  ansible.builtin.copy:
    dest: /etc/systemd/system/overseerr.service
    mode: '644'
    content: |
      [Unit]
      Description=Overseerr Daemon
      After=network.target

      [Service]
      Type=exec
      WorkingDirectory=/opt/overseerr
      ExecStart=/usr/bin/yarn start
      LimitNOFILE=32768
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Overseerr service
  ansible.builtin.systemd:
    name: overseerr
    enabled: true
    state: started

- name: Cleaning up unused and unnecessary package files
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
