- name: Install prerequisites for Bazarr
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-setuptools
      - git
      - curl
    state: present
    update_cache: true

- name: Ensure bazarr user and group with UID and GID 1000 exist
  ansible.builtin.user:
    name: bazarr
    uid: 1000
    group: bazarr
    groups: joeflix
    state: present
    create_home: false
    shell: /usr/sbin/nologin

- name: Ensure bazarr group with GID 1000 exists
  ansible.builtin.group:
    name: bazarr
    gid: 1000
    state: present

- name: Download Bazarr
  ansible.builtin.get_url:
    url: https://github.com/morpheus65535/bazarr/releases/latest/download/bazarr.zip
    dest: /opt/bazarr.zip
    mode: '755'

- name: Extract Bazarr
  ansible.builtin.unarchive:
    src: /opt/bazarr.zip
    dest: /opt/bazarr
    remote_src: true
    mode: '755'
    owner: bazarr
    group: bazarr

- name: Ensure user and group has correct rights over extracted files
  ansible.builtin.file:
    path: /opt/bazarr
    owner: bazarr
    group: bazarr
    mode: '755'
    recurse: true

- name: Create systemd service for Bazarr
  ansible.builtin.copy:
    dest: /etc/systemd/system/bazarr.service
    mode: '644'
    content: |
      [Unit]
      Description=Bazarr Daemon
      After=network.target

      [Service]
      ExecStart=/opt/bazarr/Bazarr --nobrowser --data=/opt/bazarr
      User=bazarr
      Group=bazarr
      Restart=on-failure
      LimitNOFILE=32768

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Bazarr service
  ansible.builtin.systemd:
    name: bazarr
    enabled: true
    state: started
