- name: Install prerequisites for Bazarr
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-setuptools
      - curl
      - tar
      - systemd
      - unzip
      - sudo
    state: present
    update_cache: true

- name: Ensure /var/lib/bazarr directory exists
  ansible.builtin.file:
    path: /var/lib/bazarr
    state: directory
    mode: '775'

- name: Download Bazarr
  ansible.builtin.get_url:
    url: https://github.com/morpheus65535/bazarr/releases/latest/download/bazarr.zip
    dest: /opt/bazarr.zip
    mode: '775'

- name: Extract Bazarr
  ansible.builtin.unarchive:
    src: /opt/bazarr.zip
    dest: /opt/
    remote_src: true
    mode: '775'

- name: Clean up the downloaded zip
  ansible.builtin.file:
    path: /opt/bazarr.zip
    state: absent

- name: Ensure user and group has correct rights over extracted files
  ansible.builtin.file:
    path: /opt/bazarr
    mode: '775'
    recurse: true

- name: Create systemd service for Bazarr
  ansible.builtin.copy:
    dest: /etc/systemd/system/bazarr.service
    mode: '644'
    content: |
      [Unit]
      Description=Bazarr Daemon
      After=syslog.target network.target

      [Service]
      WorkingDirectory=/opt/bazarr/
      UMask=0002
      Restart=on-failure
      RestartSec=5
      Type=simple
      ExecStart=/usr/bin/python3 /opt/bazarr/bazarr.py
      KillSignal=SIGINT
      TimeoutStopSec=20
      SyslogIdentifier=bazarr
      LimitNOFILE=16384

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Bazarr service
  ansible.builtin.systemd:
    name: bazarr
    enabled: true
    state: started

- name: Cleaning up unused and unnecessary package files
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
