- name: Install prerequisites for Prowladrr
  ansible.builtin.apt:
    name:
      - curl
      - libmono-cil-dev
      - mediainfo
      - sqlite3
      - unzip
    state: present
    update_cache: true

- name: Ensure /var/lib/prowlarr directory exists
  ansible.builtin.file:
    path: /var/lib/prowlarr
    state: directory
    mode: '775'

- name: Download Prowlarr
  ansible.builtin.get_url:
    url: https://prowlarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64
    dest: /opt/prowlarr.tar.gz
    mode: '775'

- name: Extract Prowlarr
  ansible.builtin.unarchive:
    src: /opt/prowlarr.tar.gz
    dest: /opt/
    remote_src: true
    mode: '775'

- name: Ensure user and group has correct rights over extracted files
  ansible.builtin.file:
    path: /opt/Prowlarr
    mode: '775'
    recurse: true

- name: Clean up the downloaded tarball
  ansible.builtin.file:
    path: /opt/prowlarr.tar.gz
    state: absent

- name: Create systemd service for Prowlarr
  ansible.builtin.copy:
    dest: /etc/systemd/system/prowlarr.service
    mode: '644'
    content: |
      [Unit]
      Description=Prowlarr Daemon
      After=syslog.target network.target

      [Service]
      UMask=0002
      Type=simple
      ExecStart=/opt/Prowlarr/Prowlarr -nobrowser -data=/var/lib/prowlarr/
      TimeoutStopSec=20
      KillMode=process
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Prowlarr service
  ansible.builtin.systemd:
    name: prowlarr
    enabled: true
    state: started

- name: Cleaning up unused and unnecessary package files
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
