- name: Install prerequisites for Gotify
  ansible.builtin.apt:
    name:
      - wget
      - unzip
    state: present
    update_cache: true

- name: Ensure gotify user and group with UID and GID 1000 exist
  ansible.builtin.user:
    name: gotify
    uid: 1000
    group: gotify
    groups: joeflix
    create_home: false
    state: present
    shell: /usr/sbin/nologin

- name: Ensure gotify group with GID 1000 exists
  ansible.builtin.group:
    name: gotify
    gid: 1000
    state: present

- name: Download gotify
  ansible.builtin.get_url:
    url: https://github.com/gotify/server/releases/latest/download/gotify-linux-amd64.zip
    dest: /opt/gotify.zip
    mode: '755'

- name: Extract gotify
  ansible.builtin.unarchive:
    src: /opt/gotify.zip
    dest: /opt/gotify
    remote_src: true
    mode: '755'
    owner: gotify
    group: gotify

- name: Ensure user and group has correct rights over extracted files
  ansible.builtin.file:
    path: /opt/gotify
    owner: gotify
    group: gotify
    mode: '755'
    recurse: true

- name: Create systemd service for Gotify
  ansible.builtin.copy:
    dest: /etc/systemd/system/gotify.service
    mode: '644'
    content: |
      [Unit]
      Description=Gotify Daemon
      After=network.target

      [Service]
      ExecStart=/opt/gotify/gotify
      User=gotify
      Group=gotify
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Gotify service
  ansible.builtin.systemd:
    name: gotify
    enabled: true
    state: started
