- name: Install prerequisites for Radarr
  ansible.builtin.apt:
    name:
      - curl
      - sudo
      - libmono-cil-dev
      - mediainfo
      - sqlite3
      - unzip
    state: present
    update_cache: true

- name: Ensure /var/lib/radarr directory exists
  ansible.builtin.file:
    path: /var/lib/radarr
    state: directory
    mode: '775'

- name: Download Radarr
  ansible.builtin.get_url:
    url: https://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64
    dest: /opt/radarr.tar.gz
    mode: '775'

- name: Extract Radarr
  ansible.builtin.unarchive:
    src: /opt/radarr.tar.gz
    dest: /opt/
    remote_src: true
    mode: '775'

- name: Remove Radarr tarball
  ansible.builtin.file:
    path: /opt/radarr.tar.gz
    state: absent

- name: Change ownership of Sonarr directory
  ansible.builtin.file:
    path: /opt/Radarr
    mode: '775'
    recurse: true

- name: Create systemd service for Radarr
  ansible.builtin.copy:
    dest: /etc/systemd/system/radarr.service
    mode: '644'
    content: |
      [Unit]
      Description=Radarr Daemon
      After=syslog.target network.target

      [Service]
      UMask=0002
      Type=simple
      ExecStart=/opt/Radarr/Radarr -nobrowser -data=/var/lib/radarr/
      TimeoutStopSec=20
      KillMode=process
      Restart=on-failure
      LimitNOFILE=32768

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Radarr service
  ansible.builtin.systemd:
    name: radarr
    enabled: true
    state: started

- name: Cleaning up unused and unnecessary package files
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
